time_tracker/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from core import views

urlpatterns = [
    path('', views.home, name='home'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('plans/', views.plans, name='plans'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

time_tracker/team/urls.py
from django.urls import path
from team import views

urlpatterns = [
    path('create/', views.create_team, name='create_team'),
    path('edit/', views.edit_team, name='edit_team'),
    path('invite/', views.invite, name='invite'),
    path('<int:team_id>/', views.team_detail, name='team_detail'),
    path('activate_team/<int:team_id>/', views.activate_team, name='activate_team'),
]

time_tracker/time_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

time_tracker/team/models.py
from django.db import models
from django.contrib.auth.models import User

class Team(models.Model):
    ACTIVE = 'active'
    DELETED = 'deleted'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted')
    )

    name = models.CharField(max_length=255)
    members = models.ManyToManyField(User, related_name='teams')
    created_by = models.ForeignKey(User, related_name='created_by', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, choices=CHOICES_STATUS, default=ACTIVE)

    class Meta:
        ordering = ['name', 'created_at']
    
    def __str__(self):
        return f"{self.id} - {self.name}"
    
class Invitation(models.Model):
    INVITED = 'invited'
    ACCEPTED = 'accepted'

    CHOICES_STATUS = (
        (INVITED, 'Invited'),
        (ACCEPTED, 'Accepted')
    )

    team = models.ForeignKey(Team, related_name='invitations', on_delete=models.CASCADE)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=INVITED)
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.email} - {self.status} - {self.date_sent}" 

time_tracker/team/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import random

from .models import Team, Invitation
from userprofile.models import UserProfile
from .utilities import send_invitation, invitation_accepted

@login_required
def create_team(request):
    if request.method == 'POST':
        name = request.POST.get('name')

        if name:
            team = Team.objects.create(name=name, created_by=request.user)
            team.memebers.add(request.user)
            team.save()

            userprofile = UserProfile.objects.get(user=request.user.id)
            userprofile.active_team_id = team.id
            userprofile.save()
            return redirect('mypage')
    return render(request, 'team/create_team.html')
# def active_team(request):
#     if request.user.is_authenticated:
#         if request.user.userprofile.active_team_id:
#             active_team = Team.objects.get(pk=request.user.userprofile.active_team_id)

#             return {'active_team': active_team}
#     return {'active_team': None }

@login_required
def team_detail(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    invitations = team.invitations.filter(status=Invitation.INVITED)

    return render(request, 'team/team_detail.html', {'team': team, 'invitations':invitations})

@login_required
def edit_team(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE, members__in=[request.user])

    if request.method == 'POST':
        name = request.POST.get('name')

        if name:
            team.name = name
            team.save()

            messages.info(request, 'Change Saved Successfully.')

            return redirect('team_detail', team_id = team.id)

    return render(request, 'team/edit_team.html', {'team': team})

@login_required
def activate_team(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    userprofile = request.user.userprofile
    userprofile.active_team_id = team.id
    userprofile.save()

    messages.info(request, 'The Team Was Activated.')
    return redirect('mypage')
    

@login_required
def invite(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)

    if request.method == 'POST':
        email = request.POST.get('email')

        if email:
            invitations = Invitation.objects.filter(team=team, email=email)

            if not invitations:
                code = ''.join(random.choice('abcdefghijklmnopqrstuvwxyz0123456789') for i in range(4))
                invitation = Invitation.objects.create(team=team, email=email, code=code)

                messages.info(request, 'Invitation Sent.')

                send_invitation(email, code, team)
                return redirect('team', team_id=team.id)
            else:
                messages.info(request, 'The User Has Already Been Invited.')
                return
    return render(request, 'team/invite.html', {'team': team})

time_tracker/team/templates/team/create_team.html
{% extends 'base.html' %}

{% block title %}
Create Team
{% endblock %}

{% block content %}

<nav class="breadcrumb" aria-label="breadcrumb">
    <ul>
        <li><a href="#">Dashboard</a></li>
        <li><a href="{% url 'mypage' %}">My Page</a></li>
        <li class="is-active"><a href="{% url 'create_team' %}" aria-current="page">Create Team</a></li>
    </ul>
</nav>


<div class="columns" id="team-app">
    <div class="column is-4">
        <h1 class="title">Create Team</h1>

        <form method="post" action="." class="mt-6" @submit="validateForm">
            {% csrf_token %}
            
            <div class="field">
                <label>Team Name</label>
                <div class="control">
                    <input type="text" name="name" id="id_name" v-model="name">
                </div>
            </div>

            <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">
                    [[ error ]]
                </p>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Create Team</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block script %}

<script>
    const TeamApp = {
        data() {
            return {
                name: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []
                if (this.name) {
                    return true
                }
                
                e.preventDefault()

                this.errors.push('The title field is missing.')

                return false
            }
        }
    }
    Vue.createApp(TeamApp).mount('#team-app')
</script>


{% endblock %}

time_tracker/team/templates/team/edit_team.html
{% extends 'base.html' %}

{% block title %}
Edit {{ team.name }}
{% endblock %}

{% block content %}

<nav class="breadcrumb" aria-label="breadcrumb">
    <ul>
        <li><a href="#">Dashboard</a></li>
        <li><a href="{% url 'mypage' %}">My Page</a></li>
        <li class="is-active"><a href="{% url 'edit_team' %}" aria-current="page">Edit {{ team.name }}</a></li>
    </ul>
</nav>


<div class="columns" id="team-app">
    <div class="column is-4">
        <h1 class="title">Edit Team</h1>

        <form method="post" action="." class="mt-6" @submit="validateForm">
            {% csrf_token %}
            
            <div class="field">
                <label>Team Name</label>
                <div class="control">
                    <input type="text" name="name" id="id_name" class="input" v-model="name">
                </div>
            </div>

            <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">
                    [[ error ]]
                </p>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Save Changes</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block script %}

<script>
    const TeamApp = {
        data() {
            return {
                name: '{{ team.name }}',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []
                if (this.name) {
                    return true
                }
                
                e.preventDefault()

                this.errors.push('The title field is missing.')

                return false
            }
        }
    }
    Vue.createApp(TeamApp).mount('#team-app')
</script>


{% endblock %}

time_tracker/team/templates/team/invitation_accepted.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, text/html">
    <meta http-equiv="Content-Type">
    <title>Time Tracker</title>
    <style type="text/css">
        html {
            width:100%;
        }
        body {
            width: 100%;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 14px;
            background-color: #fff;
            color: #333;
        }
        a {
            color: #111
        }

    </style>

</head>
<body>
    <table width="100%" cellspacing="0" cellpadding="0">
        <tr>
            <td><h1>Time Tracker</h1></td>
        </tr>
        <tr>
            <td>
                <p>{{ invatiation.email }} accepted your invitation</p>
            </td>
        </tr>
    </table>
    
</body>
</html>

time_tracker/team/templates/team/invitation_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, text/html">
    <meta http-equiv="Content-Type">
    <title>Time Tracker</title>
    <style type="text/css">
        html {
            width:100%;
        }
        body {
            width: 100%;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 14px;
            background-color: #fff;
            color: #333;
        }
        a {
            color: #111
        }

    </style>

</head>
<body>
    <table width="100%" cellspacing="0" cellpadding="0">
        <tr>
            <td><h1>Time Tracker - Invitation to {{ team.name }}</h1></td>
        </tr>
        <tr>
            <td>
                <p>You have been invitred to join {{ team.name }}</p>
                <p>Click the link below to sign up or login. Your team activation code is {{ code }}</p>
            </td>
        </tr>
        <tr>
            <td>
                <a href="{{ acceptation_url }}">Accept Invitation</a>
            </td>
        </tr>
    </table>
    
</body>
</html>

time_tracker/team/templates/team/invite.html
{% extends 'base.html' %}

{% block title %}
Invite Member
{% endblock %}

{% block content %}

<nav class="breadcrumb" aria-label="breadcrumb">
    <ul>
        <li><a href="#">Dashboard</a></li>
        <li><a href="{% url 'mypage' %}">My Page</a></li>
        <li><a href="{% url 'team_detail' team.id %}">{{ team.name }}</a></li>
        <li class="is-active"><a href="{% url 'invite' %}" aria-current="page">Invitation</a></li>
    </ul>
</nav>


<div class="columns is-multiline" id="invite-app">
    <div class="column is-4">
        <h1 class="title">Invitation</h1>

        <div class="notification is-danger" v-if="errors.length">
            <p v-for="error in errors">
                [[ error ]]
            </p>
        </div>

        <form method="post" action="." @submit="validateFrom" novalite>
            {% csrf_token %}
            <div class="field">
                <div class="control">
                    <label>Email</label>
                    <input type="email" name="email" id="id_email" v-model="email" class="input">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <button class="button is-success">Send Invitation</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}


{% block script %}
<script>
    const InviteApp = {
        data() {
            return {
                email: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []
                if (this.validateEmail(this.email)) {
                    return true
                }
                
                this.errors = ['Email Is Not Valid.']

                e.preventDefault()
                
                return false
            },
            validateEmail(email) {
                if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(email)) {
                    return true
                }
                return false
            }
        }
    }
    Vue.createApp(InviteApp).mount('#invite-app')
</script>


{% endblock %}

time_tracker/team/templates/team/team_detail.html
{% extends 'base.html' %}

{% block title %}
{{ team.name }}
{% endblock %}

{% block content %}

<nav class="breadcrumb" aria-label="breadcrumb">
    <ul>
        <li><a href="#">Dashboard</a></li>
        <li><a href="{% url 'mypage' %}">My Page</a></li>
        <li class="is-active"><a href="{% url 'team_detail' team.id %}" aria-current="page">{{ team.name }}</a></li>
    </ul>
</nav>


<div class="columns is-multiline" id="team-app">
    <div class="column is-4">
        <h1 class="title">{{ team.name }}</h1>

        {% if request.user == team.created_by %}
        <a class="button is-primary" href="{% url 'invite' %}">Invite</a>
        {% endif %}
        <hr>
        <h2 class="subtitle mt-6">Members</h2>
        {% for member in team.members.all %}
        <p>{{ member.username }}</p>
        {% endfor %}

        <h2 class="subtitle mt-6">Invited Members</h2>

        {% for invitation in invitations %}
        <p>{{ invitation.email }} - {{ invitation.date_sent|timesince }} ago</p>
        {% endfor %}
    </div>

    {% if team.created_by == request.user %}
    <div class="column is-12">
        <hr>
        <h3 class="subtitle">Owner Actions</h3>
        <a href="{% url 'edit_team' %}" class="button is-warning">Edit Team</a>
    </div>
    {% endif %}
</div>

{% endblock %}