time_tracker/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from core import views

urlpatterns = [
    path('', views.home, name='home'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('plans/', views.plans, name='plans'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

time_tracker/project/urls.py
from django.urls import path
from project import views, api

urlpatterns = [
    path('', views.projects, name='projects'),
    path('<int:project_id>/', views.project, name='project'),
    path('<int:project_id>/edit/', views.edit_project, name='edit_project'),
    path('<int:project_id>/<int:task_id>/', views.task, name='task'),
    path('<int:project_id>/<int:task_id>/edit/', views.edit_task, name='edit_task'),
    path('<int:project_id>/<int:task_id>/<int:entry_id>/edit/', views.edit_entry, name='edit_entry'),
    path('<int:project_id>/<int:task_id>/<int:entry_id>/delete/', views.delete_entry, name='delete_entry'),
    path('delete_untracked_entry/<int:entry_id>/', views.delete_untracked_entry, name='delete_untracked_entry'),
    path('track_entry/<int:entry_id>/', views.track_entry, name='track_entry'),

    path('api/start_timer/', api.api_start_timer, name='api_start_timer'),
    path('api/stop_timer/', api.api_stop_timer, name='api_stop_timer'),
    path('api/discard_timer/', api.api_discard_timer, name='api_discard_timer'),
    path('api/get_tasks/', api.api_get_tasks, name='api_get_tasks')
]

time_tracker/time_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

time_tracker/project/models.py
from django.db import models

from django.contrib.auth.models import User

from team.models import Team

class Project(models.Model):
    name = models.CharField(max_length=255)
    team = models.ForeignKey(Team, related_name='projects', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='projects', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['name', '-created_at']

    def __str__(self):
        return f"{self.name} - {self.created_by}"
    
    def registered_time(self):
        # time = 0

        # entries = self.entries.all()

        # for entry in entries:
        #     time = time + entries.minutes

        # return time

        return sum(entry.minutes for entry in self.entries.all())
    
    def num_tasks_todo(self):
        return self.tasks.filter(status=Task.TODO).count()
    
class Task(models.Model):

    TODO = 'todo'
    DONE = 'done'
    ARCHIVED = 'archived'

    CHOICES_STATUS = (
        (TODO, 'Todo'),
        (DONE, 'Done'),
        (ARCHIVED, 'Archived'),
    )


    name = models.CharField(max_length=255)
    team = models.ForeignKey(Team, related_name='tasks', on_delete=models.CASCADE)
    project = models.ForeignKey(Project, related_name='tasks', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='tasks', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=TODO)

    class Meta:
       ordering = ['-created_at']

    def __str__(self):
        return self.name 
    
    def registered_time(self):
        return sum(entry.minutes for entry in self.entries.all())

class Entry(models.Model):
    team = models.ForeignKey(Team, related_name='entries', on_delete=models.CASCADE)
    project = models.ForeignKey(Project, related_name='entries', on_delete=models.CASCADE, blank=True, null=True)
    task = models.ForeignKey(Task, related_name='entries', on_delete=models.CASCADE, blank=True, null=True)
    minutes = models.IntegerField(default=0)
    is_tracked = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='entries', on_delete=models.CASCADE)
    created_at = models.DateTimeField()

    class Meta:
       ordering = ['-created_at']
       verbose_name_plural = "entries"


    def __str__(self):
        if self.task:
            return '%s - %s' % (self.task.name, self.created_at)
        return '%s' % self.created_at

time_tracker/project/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from datetime import datetime

from .models import Project, Task, Entry
from team.models import Team

@login_required
def projects(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    projects = Project.objects.all()

    if request.method == 'POST':
        name = request.POST.get('name')

        if name:
            project = Project.objects.create(team=team, name=name, created_by=request.user)

            messages.info(request, 'The Project Is Added.')

            return redirect('projects')

    return render(request, 'project/projects.html', {'team': team, 'projects': projects})

@login_required
def project(request, project_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)

    if request.method == 'POST':
        name = request.POST.get('name')

        if name:
            task = Task.objects.create(team=team, project=project, name=name, created_by=request.user)

            messages.info(request, 'The Task Is Added.')

            return redirect('project', project_id=project.id)
        
    tasks_todo = project.tasks.filter(status=Task.TODO)
    tasks_done = project.tasks.filter(status=Task.DONE)

    return render(request, 'project/project.html', {'team':team, 'project':project, 'tasks_todo':tasks_todo, 'tasks_done':tasks_done})

@login_required
def edit_project(request, project_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)

    if request.method == 'POST':
        name = request.POST.get('name')

        if name:
            project.name = name
            project.save()

            messages.info(request, 'The Project Is Updated.')

            return redirect('project', project_id=project.id)



    return render(request, 'project/edit_project.html', {'team':team, 'project':project})

@login_required
def task(request, project_id, task_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)

    if request.method == 'POST':
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))
        date = '%s %s' % (request.POST.get('date'), datetime.now().time())
        minutes_total = (hours * 60) + minutes

        entry = Entry.objects.create(team=team, project=project, task=task, minutes=minutes_total, created_by=request.user, created_at=date, is_tracked=True)
        return redirect('task', project_id=project.id, task_id=task.id)
    return render(request, 'project/task.html', {'team':team, 'project':project, 'task':task, 'today': datetime.today()})

@login_required
def edit_task(request, project_id, task_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)

    if request.method == 'POST':
        name = request.POST.get('name')
        status = request.POST.get('status')

        if name:
            task.name = name
            task.status = status
            task.save()

            messages.info(request, 'The Task Is Updated.')

            return redirect('task', project_id=project.id, task_id=task.id)



    return render(request, 'project/edit_task.html', {'team':team, 'project':project, 'task':task})

@login_required
def edit_entry(request, project_id, task_id, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)

    if request.method == 'POST':
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))
        date = '%s %s' % (request.POST.get('date'), datetime.now().time())

        entry.created_at = date
        entry.minutes = (hours * 60) + minutes
        entry.save()

        messages.info(request, 'The Entry Is Updated.')

        return redirect('task', project_id=project.id, task_id=task.id)
    
    hours, minutes = divmod(entry.minutes, 60)

    return render(request, 'project/edit_entry.html', {'team':team, 'project':project, 'task':task, 'entry': entry, 'hours': hours, 'minutes':minutes})

@login_required
def delete_entry(request, project_id, task_id, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    project = get_object_or_404(Project, team=team, pk=project_id)
    task = get_object_or_404(Task, pk=task_id, team=team)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)

    entry.delete()

    messages.info(request, 'The Entry Is Deleted.')

    return redirect('task', project_id=project.id, task_id=task.id)

@login_required
def delete_untracked_entry(request, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)

    entry.delete()

    messages.info(request, 'The Entry Is Deleted.')

    return redirect('dashboard')

@login_required
def track_entry(request, entry_id):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE)
    entry = get_object_or_404(Entry, pk=entry_id, team=team)
    projects = team.projects.all()

    if request.method == 'POST':
        hours = int(request.POST.get('hours', 0))
        minutes = int(request.POST.get('minutes', 0))
        project = request.POST.get('project')
        task = request.POST.get('task')

        if project and task:
            entry.project_id = project
            entry.task_id = task
            entry.minutes = (hours * 60) + minutes
            entry.created_at = '%s %s' % (request.POST.get('date'), entry.created_at.time())
            entry.is_tracked = True
            entry.save()



            messages.info(request, 'The Time Has Been Tracked')

            return redirect('dashboard')
        
    hours, minutes = divmod(entry.minutes, 60)

    context = {
        'hours': hours,
        'minutes': minutes,
        'team': team,
        'projects': projects,
        'entry': entry
    }

    return render(request, 'project/track_entry.html', context)

time_tracker/project/templates/project/edit_entry.html
{% extends 'base.html' %}

{% block title %}
Edit Entry
{% endblock %}

{% block content %}
<div id="project-app">
    <nav class="breadcrumb" aria-label="breadcrumb">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'projects' %}">Projects</a></li>
            <li><a href="{% url 'project' project.id %}">{{ project.name }}</a></li>
            <li><a href="{% url 'task' project.id task.id%}" aria-current="page">{{ task.name }}</a></li>
            <li class="is-active"><a href="{% url 'edit_entry' project.id task.id entry.id %}" aria-current="page">Edit Entry</a></li>
        </ul>
    </nav>
</div>
    
<div class="columns mt-2">
    <div class="column is-4">
        <h1 class="title">Edit Entry</h1>

        <form method="post" action=".">
            {% csrf_token %}
            <div class="field is-grouped">
                <div class="control">
                    <div class="select">
                        <select name="hours">
                            <option value="0"{% if hours == 0 %} selected {% endif %}>0 h</option>
                            {% for i in 'x'|rjust:'10' %}
                            <option value="{{ forloop.counter }}"{% if hours == forloop.counter %} selected {% endif %}>{{ forloop.counter }} h</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                
                <div class="control">
                    <div class="select">
                        <select name="minutes">
                            <option value="0"{% if minutes == 0 %} selected {% endif %}>0 m</option>
                            {% for i in 'x'|rjust:'59' %}
                            <option value="{{ forloop.counter }}"{% if minutes == forloop.counter %} selected {% endif %}>{{ forloop.counter }} m</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <label>Date</label>
                <div class="control">
                    <input type="date" id="id_date" name="date" class="input" value="{{ entry.created_at|date:'Y-m-d' }}" placeholder="yyyy-mm-dd">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

time_tracker/project/templates/project/edit_project.html
{% extends 'base.html' %}

{% block title %}
Edit Project
{% endblock %}

{% block content %}
<div  id="project-app">
    <nav class="breadcrumb" aria-label="breadcrumb">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'projects' %}">Projects</a></li>
            <li><a href="{% url 'project' project.id %}">{{ project.name }}</a></li>
            <li class="is-active"><a href="{% url 'edit_project' project.id %}" aria-current="page">Edit Project</a></li>
        </ul>
    </nav>
</div>
    
<div class="columns">
    <div class="column is-4">
        <h1 class="title">Edit Project</h1>

        <form method="post" action=".">
            {% csrf_token %}
            
            <div class="field">
                <label>Project Name</label>
                <div class="control">
                    <input type="text" name="name" id="id_name" class="input" value="{{ project.name }}">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Save Changes</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

time_tracker/project/templates/project/edit_task.html
{% extends 'base.html' %}

{% block title %}
Edit Task
{% endblock %}

{% block content %}
<div  id="project-app">
    <nav class="breadcrumb" aria-label="breadcrumb">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'projects' %}">Projects</a></li>
            <li><a href="{% url 'project' project.id %}">{{ project.name }}</a></li>
            <li class="is-active"><a href="{% url 'edit_task' project.id task.id %}" aria-current="page">Edit Task</a></li>
        </ul>
    </nav>
</div>
    
<div class="columns">
    <div class="column is-4">
        <h1 class="title">Edit Task</h1>

        <form method="post" action=".">
            {% csrf_token %}
            
            <div class="field">
                <label>Task Name</label>
                <div class="control">
                    <input type="text" name="name" id="id_name" class="input" value="{{ task.name }}">
                </div>
            </div>

            <div class="field">
                <label>Status</label>
                <div class="control">
                    <div class="select">
                        <select name="status" id="id_status">
                            <option value="todo"{% if task.status == 'todo' %} selected {% endif %}>Todo</option>
                            <option value="done"{% if task.status == 'done' %} selected {% endif %}>Done</option>
                        </select>
                    </div>    
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Save Changes</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

time_tracker/project/templates/project/project.html
{% extends 'base.html' %}

{% block title %}
{{ project.name }}
{% endblock %}

{% block content %}
<div  id="project-app">
    <nav class="breadcrumb" aria-label="breadcrumb">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'projects' %}" aria-current="page">Projects</a></li>
            <li class="is-active"><a href="{% url 'project' project.id %}" aria-current="page">{{ project.name }}</a></li>
        </ul>
    </nav>

    <div class="columns">
        <div class="column is-4">
            <h1 class="title">{{ project.name }}</h1>

            <div class="buttons">
                <a href="{% url 'edit_project' project.id %}" class="button is-warning">Edit Project</a>
                <a @click="showTaskModal=!showTaskModal" class="button is-success">Add Task</a>
            </div>
        </div>
    </div>

    {% if not tasks_todo and not tasks_done %}
        <div class="columns">
            <div class="column is-3">
                <div class="notification">
                    <p>No Task Yet.</p>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="columns is-multiline">
        {% if tasks_todo %}
        <div class="column is-12">
            <h2 class="is-size-4">Todo</h2>
        </div>
        

        {% for task in tasks_todo %}
            <div class="column is-2">
                <div class="notification">
                    <h3 class="is-size-5">{{ task.name }}
                    </h3>
                    <p>Registered Time: {{ task.registered_time }}</p>
                    <hr>

                    <a class="button is-success" href="{% url 'task' project.id task.id %}">Details</a>
                </div>
            </div>
        {% endfor %}
        {% endif %}
        <hr>

        {% if tasks_done %}
        <div class="column is-12">
            <h2 class="is-size-4">Done</h2>
        </div>

        {% for task in tasks_done %}
        <div class="column is-2">
            <div class="notification">
                <h3 class="is-size-5">{{ task.name }}
                </h3>
                <p>Registered Time: {{ task.registered_time }}</p>
                <hr>

                <a class="button is-success" href="{% url 'task' project.id task.id %}">Details</a>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>

    <div class="modal" :class="{'is-active': showTaskModal}">
        <div class="modal-background">
            <form method="post" action="." @submit="validateForm">
                {% csrf_token %}
                <div class="modal-card mt-6">
                    <div class="modal-card-head">
                        <p class="modal-card-title">Add Task</p>
                    </div>
                    <div class="modal-card-body">
                        <div class="field">
                            <label>Task Name</label>
                            <div class="control">
                                <input type="text" name="name" id="id_name" v-model="name" class="input">
                            </div>
                        </div>

                        <div class="notification is-danger" v-if="showErrors">
                            Task Name Is Missing.
                        </div>
                    </div>
                    <div class="modal-card-foot">
                        <button class="button is-success">Add</button>
                        <button class="button" @click="showTaskModal=!showTaskModal">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}


{% block script %}
<script>
    const ProjectApp = {
        data() {
            return {
                showTaskModal: false,
                name: '',
                showErrors: false
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                if (this.name) {
                    return true
                }
                this.showErrors = true
                
                e.preventDefault()

                return false
            }
        }
    }

    Vue.createApp(ProjectApp).mount('#project-app')
</script>

{% endblock %}

time_tracker/project/templates/project/projects.html
{% extends 'base.html' %}

{% load dashboardextras %}

{% block title %}
Projects
{% endblock %}

{% block content %}
<div  id="projects-app">
    <nav class="breadcrumb" aria-label="breadcrumb">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li class="is-active"><a href="{% url 'projects' %}" aria-current="page">Project</a></li>
        </ul>
    </nav>
    
    <div class="columns">
        <div class="column is-4">
            <h1 class="title">Projects</h1>

            <a @click="showProjectModal=!showProjectModal" class="button is-success">Create Project</a>
        </div>
    </div>

    <div class="columns">
        {% for project in projects %}
        <div class="column is-3">
            <div class="notification">
                <h2 class="is-size-5">{{ project.name }}</h2>
                <p class="is-size-7 mb-2">({{ project.created_by }})</p>
                <p class="is-size-7">Registered Time: {{ project.registered_time|format_minutes }} minutes</p>
                <p class="is-size-7">Tasks: {{ project.num_tasks_todo }}</p>

                <hr>

                <a href="{% url 'project' project.id %}" class="button is-success">Details</a>

            </div>
        </div>

        {% empty %}
        <div class="column is-3">
            <div class="notification">
                No projects yet...
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="modal" :class="{'is-active': showProjectModal}">
        <div class="modal-background">
            
            <form method="post" action="." @submit="validateForm">
                {% csrf_token %}
                <div class="modal-card mt-6">
                    <div class="modal-card-head">
                        <p class="modal-card-title">Create Project</p>
                    </div>
                    <div class="modal-card-body">
                        <div class="field">
                            <label>Project Name</label>
                            <div class="control">
                                <input type="text" name="name" id="id_name" v-model="name" class="input">
                            </div>
                        </div>

                        <div class="notification is-danger" v-if="showErrors">
                            Project Name Is Missing.
                        </div>
                    </div>
                    <div class="modal-card-foot">
                        <button class="button is-success">Create</button>
                        <button class="button" @click="showProjectModal=!showProjectModal">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    

    </div>
</div>
{% endblock %}

{% block script %}
<script>
    const ProjectsApp = {
        data() {
            return {
                showProjectModal: false,
                name: '',
                showErrors: false
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                if (this.name) {
                    return true
                }
                this.showErrors = true
                
                e.preventDefault()

                return false
            }
        }
    }

    Vue.createApp(ProjectsApp).mount('#projects-app')
</script>

{% endblock %}

time_tracker/project/templates/project/task.html
{% extends 'base.html' %}

{% block title %}
{{ task.name }}
{% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumb">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'projects' %}" aria-current="page">Projects</a></li>
            <li><a href="{% url 'project' project.id %}">{{ project.name }}</a></li>
            <li class="is-active"><a href="{% url 'task' project.id task.id %}" aria-current="page">{{ task.name }}</a></li>
        </ul>
    </nav>

    <div class="columns">
        <div class="column is-4">
            <h1 class="title">{{ task.name }} ({{ task.get_status_display }})</h1>
            <a href="{% url 'edit_task' project.id task.id %}" class="button is-warning">Edit Task</a>
            
            <hr>

            <h2 class="subtitle">Register Time</h2>

            <form method="post" action=".">
                {% csrf_token %}
                <div class="field is-grouped">
                    <div class="control">
                        <div class="select">
                            <select name="hours">
                                <option value="0">0 h</option>
                                {% for i in 'x'|rjust:'10' %}
                                <option value="{{ forloop.counter }}">{{ forloop.counter }} h</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    
                    <div class="control">
                        <div class="select">
                            <select name="minutes">
                                <option value="0">0 m</option>
                                {% for i in 'x'|rjust:'59' %}
                                <option value="{{ forloop.counter }}">{{ forloop.counter }} m</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>

                <div class="field">
                    <label>Date</label>
                    <div class="control">
                        <input type="date" id="id_date" name="date" class="input" value="{{ today|date:'Y-m-d' }}" placeholder="yyyy-mm-dd">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="columns">
        <div class="column is-12">
            <hr>

            <h2 class="subtitle">Logged Entries</h2>

            {% if task.entries.all %}
            <table class="table is-full-width" style="text-align: left;">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>User</th>
                        <th>Time</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    {% for entry in task.entries.all %}
                    <tr>
                        <td>{{ entry.created_at }}</td>
                        <td>{% firstof entry.created_by.get_full_name entry.created_by.username %}</td>
                        <td>{{ entry.minutes }}</td>
                        <td>
                            <a class="button is-warning" href="{% url 'edit_entry' project.id task.id entry.id  %}">Edit</a>
                            <a class="button is-danger" href="{% url 'delete_entry' project.id task.id entry.id  %}">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>

                <tfoot>
                    <tr>
                        <th colspan="2">Total</th>
                        <th colspan="2">{{ task.registered_time }}</th>
                    </tr>
                </tfoot>
            </table>
            {% else %}
            <p>No Entries Yet.</p>
            {% endif %}
        </div>
    </div>

{% endblock %}