time_tracker/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from core import views

urlpatterns = [
    path('', views.home, name='home'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('plans/', views.plans, name='plans'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

time_tracker/time_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

time_tracker/userprofile/urls.py
from django.urls import path
from userprofile import views

urlpatterns = [
    path('mypage/', views.mypage, name='mypage'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('accept_invitation/', views.accept_invitation, name='accept_invitation'),
]

time_tracker/team/models.py
from django.db import models
from django.contrib.auth.models import User

class Team(models.Model):
    ACTIVE = 'active'
    DELETED = 'deleted'

    CHOICES_STATUS = (
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted')
    )

    name = models.CharField(max_length=255)
    members = models.ManyToManyField(User, related_name='teams')
    created_by = models.ForeignKey(User, related_name='created_by', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, choices=CHOICES_STATUS, default=ACTIVE)

    class Meta:
        ordering = ['name', 'created_at']
    
    def __str__(self):
        return f"{self.id} - {self.name}"
    
class Invitation(models.Model):
    INVITED = 'invited'
    ACCEPTED = 'accepted'

    CHOICES_STATUS = (
        (INVITED, 'Invited'),
        (ACCEPTED, 'Accepted')
    )

    team = models.ForeignKey(Team, related_name='invitations', on_delete=models.CASCADE)
    email = models.EmailField()
    code = models.CharField(max_length=20)
    status = models.CharField(max_length=20, choices=CHOICES_STATUS, default=INVITED)
    date_sent = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.email} - {self.status} - {self.date_sent}" 

time_tracker/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)
    active_team_id = models.IntegerField(default=0)
    avatar = models.ImageField(upload_to='uploads/avatars/', blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    def get_avatar(self):
        if self.avatar:
            return self.avatar.url
        else:
            return '/static/images/avatar.jpg'

time_tracker/userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from team.models import Team, Invitation
from team.utilities import invitation_accepted


@login_required
def mypage(request):
    teams = Team.objects.exclude(pk=request.user.userprofile.active_team_id)
    invitations = Invitation.objects.filter(email=request.user.email, status=Invitation.INVITED)

    return render(request, 'user/mypage.html', {'teams':teams, 'invitations':invitations})

@login_required
def edit_profile(request):
    if request.method == 'POST':
        request.user.first_name = request.POST.get('first_name')
        request.user.last_name = request.POST.get('last_name')
        request.user.email = request.POST.get('email')
        request.user.save()

        if request.FILES:
            avatar = request.FILES['avatar']
            userprofile = request.user.userprofile
            userprofile.avatar = avatar
            userprofile.save()

        messages.success(request, 'Your Profile Has Been Updated.')
        return redirect('mypage')

    return render(request, 'user/edit_profile.html')

@login_required
def accept_invitation(request):
    if request.method == 'POST':
        code = request.POST.get('code')
        email = request.user.email
        invitations = Invitation.objects.filter(code=code, email=email)

        if invitations:
            invitation = invitations[0]
            invitation.status = Invitation.ACCEPTED
            invitation.save()

            team = invitation.team
            team.members.add(request.user)
            team.save()

            userporfile = request.user.userprofile
            userporfile.active_team_id = team.id
            userporfile.save()

            messages.info(request, 'Invitation Accepted.')

            invitation_accepted(email, team, invitation)

            return redirect('team', team_id=team.id)
        else:
            messages.info(request, 'Invitation Not Found.')
            return redirect('mypage')
    else:
        return render(request, 'user/accept_invitation.html')

time_tracker/userprofile/templates/user/accept_invitation.html
{% extends 'base.html' %}

{% block title %}
Accept Invitation
{% endblock %}

{% block content %}

<nav class="breadcrumb" aria-label="breadcrumb">
    <ul>
        <li><a href="#">Dashboard</a></li>
        <li><a href="{% url 'mypage' %}">My Page</a></li>
        <li class="is-active"><a href="{% url 'accept_invitation' %}" aria-current="page">Accept Invitation</a></li>
    </ul>
</nav>


<div class="columns">
    <div class="column is-4">
        <h1 class="title">Accept Invitaion</h1>
        <form method="post" action=".">
            {% csrf_token %}

            <div class="field">
                <label>Verification Code</label>
                <div class="control">
                    <input type="text" name="code" id="id_code" class="input">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <button class="button is-success">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

time_tracker/userprofile/templates/user/edit_profile.html
{% extends 'base.html' %}

{% block title %}
Edit Profile
{% endblock %}

{% block content %}

<nav class="breadcrumb" aria-label="breadcrumb">
    <ul>
        <li><a href="#">Dashboard</a></li>
        <li><a href="{% url 'mypage' %}">My Page</a></li>
        <li class="is-active"><a href="{% url 'edit_profile' %}" aria-current="page">Edit Profile</a></li>
    </ul>
</nav>


<div class="columns">
    <div class="column is-4">
        <h1 class="title">Edit Profile</h1>
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            

            <div class="field">
                <label>Avatar</label>
                <figure class="image is-64x64">
                    <img src="{{ request.user.userprofile.get_avatar }}">
                </figure>
                <div class="control mt-2">
                    <input type="file" name="avatar" id="id_avatar" class="input">
                </div>
            </div>

            <div class="field">
                <label>First Name</label>
                <div class="control">
                    <input type="text" name="first_name" id="first_name" class="input" {% if request.user.first_name %} value="{{ request.user.first_name }}" {% endif %}>
                </div>
            </div>

            <div class="field">
                <label>Last Name</label>
                <div class="control">
                    <input type="text" name="last_name" class="input" {% if request.user.last_name %} value="{{ request.user.last_name }}" {% endif %}>
                </div>
            </div>

            <div class="field">
                <label>Email</label>
                <div class="control">
                    <input type="email" name="email" class="input" {% if request.user.email %} value="{{ request.user.email }}" {% endif %}>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

time_tracker/userprofile/templates/user/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}

{% block content %}
<section class="hero is-medium is-light is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Login</h1>
            <h2 class="subtitle">Login To Your Account</h2>
        </div>
    </div>
</section>

<div class="columns" id="signup-app">
    <div class="column is-6 is-offset-3">
        <form method="post" action="." class="mt-6">
            {% csrf_token %}

            {% if form.errors %}
            <div class="notification is-danger">
                {{ form.non_field_errors }}

                {% for field in form %}
                    {% if field.errors %}
                        {{ field.label }}: {{ field.errors|striptags }}
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}

            <div class="field">
                <label>E-mail</label>
                <div class="control">
                    <input type="email" name="username" id="id_username" class="input" v-model="username">
                </div>
            </div>

            <div class="field">
                <label>Password</label>
                <div class="control">
                    <input type="password" name="password" id="id_password" class="input">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Login</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

time_tracker/userprofile/templates/user/mypage.html
{% extends 'base.html' %}

{% block title %}
My Page
{% endblock %}

{% block content %}

<nav class="breadcrumb" aria-label="breadcrumb">
    <ul>
        <li class="is-active"><a href="{% url 'mypage' %}">My Page</a></li>
    </ul>
</nav>
<div class="columns">
    <div class="column is-6">
        <div class="media mb-4">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="{{ user.userprofile.get_avatar }}">
                </figure>
            </div>
            <div class="media-content">
                <p class="title is-3">{% firstof user.get_full_name user.username %}</p>
                <p class="subtitle is-6">{{ user.email }}</p>
            </div>
        </div>

        <form method="post" action="{% url 'logout' %}" class="column">
            {% csrf_token %}
            <a href="{% url 'edit_profile' %}" class="button is-info">Edit Profile</a>
            <button class="button is-danger" type="submit">Logout</button>
        </form>
        </div>
    </div>
</div>

<hr>

<div class="columns">
    <div class="column is-12">
        <a href="{% url 'create_team' %}" class="button is-success">Create Team</a>
    </div>
</div>

{% if invitations %}
<div class="notification is-info">
    <h2 class="subtitle">Pending Invitations</h2>
    {% for invitation in invitations %}
    <a href="{% url 'accept_invitation' %}">{{ invitation.team.name }}</a>
    {% endfor %}
</div>
{% endif %}

<div class="columns">
    {% if active_team %}
    <div class="column is-4">
        <div class="notification has-background-success-light">
            <h3 class="is-size-5">{{ active_team.name }}{% if active_team.created_by == request.user %}(owner){% else %}(member){% endif %}</h3>

            <h3 class="is-size-6">SHOW PLAN HERE</h3>
            
            <hr>
            
            <a href="{% url 'team_detail' active_team.id %}" class="button is-success">Details</a>
            {% if active_team.created_by == request.user %}
            <a href="{% url 'invite' %}" class="button is-info">Invite</a>
            {% endif %}
        </div>
    </div>
    {% endif %} 

    {% for team in teams %}
    <div class="column is-4">
        <div class="notification">
            <h3 class="is-size-5">{{ team.name }}{% if team.created_by == request.user %}(owner){% else %}(member){% endif %}</h3>

            <h3 class="is-size-6">SHOW PLAN HERE</h3>

            <hr>

            <a href="{% url 'team_detail' team.id %}" class="button is-success">Details</a>
            <a href="{% url 'activate_team' team.id %}" class="button is-info">Activate</a>
        </div>
    </div>
{% endfor %}
</div>



{% endblock %}

time_tracker/userprofile/templates/user/signup.html
{% extends 'base.html' %}

{% block title %}
Sign Up
{% endblock %}

{% block content %}
<section class="hero is-medium is-light is-bold">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Sign Up</h1>
            <h2 class="subtitle">Get Your Journey Started.</h2>
        </div>
    </div>
</section>

<div class="columns" id="signup-app">
    <div class="column is-6 is-offset-3">
        <form method="post" action="." class="mt-6" v-on:submit="validateForm" novalidate>
            {% csrf_token %}

            {% if form.errors %}
            <div class="notification is-danger">
                {{ form.non_field_errors }}

                {% for field in form %}
                    {% if field.errors %}
                        {{ field.label }}: {{ field.errors|striptags }}
                    {% endif %}
                {% endfor %}
            </div>
            {% endif %}

            <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">
                    [[ error ]]
                </p>
            </div>

            <div class="field">
                <label>E-mail</label>
                <div class="control">
                    <input type="email" name="username" id="id_username" class="input" v-model="username">
                </div>
            </div>

            <div class="field">
                <label>Password</label>
                <div class="control">
                    <input type="password" name="password1" id="id_password1" class="input" v-model="password1">
                </div>
            </div>

            <div class="field">
                <label>Comfirm Password</label>
                <div class="control">
                    <input type="password" name="password2" id="id_password2" class="input" v-model="password2">
                </div>
            </div>

            <ul class="password-help-text">
                <li v-if="password1.length < 8">Your Password Must Contain At Least 8 Characters.</li>
                <li v-if="!isNaN(password1)">Your Password Must Contain At Least 1 Alphabet.</li>
            </ul>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Sign Up</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

{% block script %}

<script>
    const SignupApp = {
        data() {
            return {
                username: '',
                password1: '',
                password2: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (!this.validateEmail(this.username)) {
                    this.errors.push('Your Email Is Not Valid.')
                }

                // if (this.password1 === '') {
                //     this.errors.push('Your Password Is Missing.')
                // }
                // if (this.password1.length < 8 ) {
                //     this.errors.push('Your Password Must Be At Least 8 Characters.')
                // }
                // if (!isNaN(password1)) {
                //     this.errors.push('Your Password Must Contain At Least 1 Alphabet.')
                // }
                // if (this.password1 !== this.password2) {
                //     this.errors.push('Your Passwords Do Not Match.')
                // }

                if (this.errors.length) {
                    e.preventDefault()
                    return false
                } else {
                    return true
                }

            },
            validateEmail(email) {
                if (/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(email)) {
                    return true
                }
                return false
            }
        }
    }
    
    Vue.createApp(SignupApp).mount('#signup-app')
</script>

{% endblock %}